#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=16
#PBS -N Alpha_2018
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TEMPDIR=~/qiime_tmp
source activate qiime1
time alpha_diversity.py \
-i ~/2018_02_smb/Silva_otus/otu_table.biom \
-o ~/2018_02_smb/AlphaDiversityChao1 \
-m chao1,PD_whole_tree \
-t ~/2018_02_smb/SILVA_128_QIIME_release/trees/97/97_otus.tre
source deactivate
