#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=16
#PBS -N compare_pH
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
module load R-3.3.1-gcc-6.2.0-zjrjm3s
export TEMPDIR=~/qiime_tmp
source activate qiime1
time compare_categories.py \
--method adonis \
-i ~/2018_02_smb/Silva_otu_diversity/bdiv_even625/unweighted_unifrac_dm.txt \
-m map.txt row.names=NULL \
-o ~/2018_02_smb/Categories_pH \
-c SamplePh \
-n 999
source deactivate
