#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=16
#PBS -N Rm_ambiguous_L2
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TEMPDIR=~/qiime_tmp
source activate qiime1
time filter_taxa_from_otu_table.py \
-i ~/2018_02_smb/Silva_otu_diversity/taxa_plots/table_mc625_L2.biom \
-o ~/2018_02_smb/Silva_otu_diversity/taxa_plots/Table_L2_filtered.biom \
-n Ambiguous_taxa
source deactivate
