#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=16
#PBS -N Top_10_phyla
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TEMPDIR=~/qiime_tmp
source activate qiime1
time filter_taxa_from_otu_table.py \
-i ~/2018_02_smb/Silva_otu_diversity/taxa_plots/table_mc625_sorted_L2.biom \
-o ~/2018_02_smb/Silva_otu_diversity/taxa_plots \
-p D1_Verrucomicrobia,D1_Proteobacteria,D1_Bacteroidetes,D1_Actinobacteria,D1_Acidobacteria,D1_Thaumarchaeota,D1_Planctomycetes,D1_Chloroflexi,D1_Gemmatimonadetes,D1_Nitrospirae
source deactivate
