#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_join_paired_ends
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
source activate qiime1
export TMPDIR=~/qiime_tmp
#joining paired ends
echo "join paired ends SeqPrep"
time join_paired_ends.py -m SeqPrep -f Read1.fastq.gz -r Read2.fastq.gz -b Index.fastq.gz -o ~/2018_02_smb/Seqprep_joined
source deactivate
