#! /bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1 ncpus=32
#PBS -N 2018_Pick_open_otus
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
source activate qiime1
echo 'picking_open_otus'
pick_open_reference_otus.py \
-i ~/2018_02_smb/slout/seqs.fna \
-o ~/2018_02_smb/otus \
-r ~/SILVA_128_QIIME_release/rep_set_aligned/97/97_outs_aligned_fasta.gz \
-s 0.001 \
--prefilter_percent_id 0.0 \
-a \
-O 32
source deactivate
