#! /bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=72
#PBS -L place=excl
#PBS -N 2018_Pick_closed_otus
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1
echo 'picking_closed_otus'
time pick_closed_reference_otus.py \
-i ~/2018_02_smb/slout/seqs.fna \
-o ~/2018_02_smb/closed_otus \
-r ~/2018_02_smb/SILVA_128_QIIME_release/rep_set_aligned/97/97_otus_aligned.fasta.gz \
-a -O 36
source deactivate
