#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=16
#PBS -N group_significance_Veg
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TEMPDIR=~/qiime_tmp
source activate qiime1
time group_significance.py \
-i ~/2018_02_smb/Silva_otu_diversity/taxa_plots/table_mc625_sorted_L2.biom \
-o ~/2018_02_smb/GroupSignificance/GroupSignificanceVeg \
-c SampleVegetation \
-m map.txt \
-s kruskal_wallis
source deactivate
