#! /bin/bash --login
#PBS -l select=1:ncpus=48
#PBS -l walltime=01:00:00
#PBS -N Silva_core_diversity
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1
echo 'Core Diversity Analyses'
time core_diversity_analyses.py \
--recover_from_failure \
-i ~/2018_02_smb/Silva_otus/otu_table.biom \
-t ~/2018_02_smb/SILVA_128_QIIME_release/trees/97/97_otus.tre \
-o ~/2018_02_smb/Silva_otu_diversity \
-m map.txt \
-e 625 \
-O 24
source deactivate
