#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=16
#PBS -N Principle_coordinates
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TEMPDIR=~/qiime_tmp
source activate qiime1
time principle_coordinates.py \
-i ~/2018_02_smb/Silva_otu_diversity/bdiv_even625/weighted_unifrac_dm.txt \
-o ~/2018_02_smb/Silva_otudiversity/bdiv_even625/weighted_dm_coords.txt
source deactivate
